### ISSUE TITLE
mNativeAd.getAdStarRating() in FacebookNative.java as been Deprecated

### ISSUE THREAD

**Issue by aaronstanley** [mopub/mopub-android-mediation#14]
While using this to obtain a Native ad, I am getting the following NullPointerException.

`java.lang.NullPointerException: Attempt to invoke virtual method 'double com.facebook.ads.internal.n.g.a()' on a null object reference
                                                                              at com.facebook.ads.NativeAd$Rating.getValue(Unknown Source)
                                                                              at com.mopub.nativeads.FacebookNative$FacebookStaticNativeAd.getDoubleRating(FacebookNative.java:250)
                                                                              at com.mopub.nativeads.FacebookNative$FacebookStaticNativeAd.onAdLoaded(FacebookNative.java:170)
                                                                              at com.facebook.ads.NativeAd$1.a(Unknown Source)`

Mopub SDK version 4.20
Facebook Audience Network SDK version 4.28.0

**Comment by rsatrasala** [comment]
Thank you @aaronstanley. We will look into this and get back to you.

**Comment by rsatrasala** [comment]
@aaronstanley The issue is because of the change in the behavior of Facebook's getAdStarRating(). We are working with Facebook team to figure out the cause. We will keep you posted.

**Comment by chauduyphanvu1** [comment]
@aaronstanley Thanks for the report - we worked with FB and were told that a fix will be shipped with the 4.28.1 release of their SDK. Currently we recommend either using the 4.27 release of the Facebook Audience Network SDK or waiting for the 4.28.1 release to avoid this crash. We'll also release a new version of the adapters once we have completed the certification.

**Comment by chauduyphanvu1** [comment]
@aaronstanley We removed the star rating code from the FacebookNative adapter since that asset has been deprecated by Facebook. This should resolve the crash - let us know!

**Comment by aaronstanley** [comment]
@chauduyphanvu1 Looks fine to me. Probably the safest solution to remove it now before getAdStarRating() vanishes from the FB codebase entirely anyway.

Cheers for the update!
