### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.mopub.MoPubMediationLog

### ISSUE THREAD

**Issue by photog0411** [mopub/mopub-android-mediation#24]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mopub/MoPubMediationLog;
        at com.mopub.mobileads.GooglePlayServicesInterstitial.loadInterstitial(GooglePlayServicesInterstitial.java:37)
        at com.mopub.mobileads.CustomEventInterstitialAdapter.loadInterstitial(CustomEventInterstitialAdapter.java:85)
        at com.mopub.mobileads.MoPubInterstitial$MoPubInterstitialView.loadCustomEvent(MoPubInterstitial.java:462)
        at com.mopub.mobileads.AdViewController.loadCustomEvent(AdViewController.java:191)
        at com.mopub.mobileads.AdViewController.onAdLoadSuccess(AdViewController.java:150)
        at com.mopub.mobileads.AdViewController$1.onSuccess(AdViewController.java:120)
        at com.mopub.network.AdRequest.deliverResponse(AdRequest.java:368)
        at com.mopub.network.AdRequest.deliverResponse(AdRequest.java:47)
        at com.mopub.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by chauduyphanvu1** [comment]
Hi, sorry for this glitch. Please use the previous version of the adapters whenever possible until this is resolved. We'll deploy a newer version (incremented by 0.0.0.1) with the fix.

**Comment by photog0411** [comment]
The weird thing is if I look at GooglePlayServicesInterstitial.java for your version 15.0.0.0 on this github repo, it doesn't have the references to MoPubMediationLog  that is causing the app crash.

But If I implement version 15.0.0.0 into my app using Gradle direct import, the decompiled jar file has the MoPubMediationLog references that are causing the crash.

Strange? I wonder if the 15.0.0.0 version you have on Maven is the incorrect version.


Any way, I can confirm that lowering my gradle import version down to 
'com.mopub.mediation:admob:11.8.0.0'

did fix the NoClassDefFoundError.

**Comment by chauduyphanvu1** [comment]
Yeah the new class must have made its way in right after the deploy to GitHub and before the deploy to JCenter (our release happens in that order). I'll remove the new class as soon as I get to my computer (i.e. soon). Thanks for flagging!

If you still want to use Play services 15.0.0 you can use the adapter binaries from this repo.

**Comment by photog0411** [comment]
Thank you for your fast replies.

Will you be updating the version number after you fix it, or should I just re-import from Jcenter the same version and rebuild my APK?

**Comment by chauduyphanvu1** [comment]
I'll increment it to 15.0.0.1. I'll let you know once it's in prod, and you can ask Gradle to resync.

**Comment by photog0411** [comment]
Thank you very much.

The weird thing is this crash is only happening on 3 out of 9 of my apps that have mopub integrated, even though I integrated mopub into them all at the same time (2 days ago).

**Comment by chauduyphanvu1** [comment]
This should be fixed now. Can you try again with `implementation 'com.mopub.mediation:admob:15.0.0.1'`? Thanks!

**Comment by radi-cho** [comment]
I had similar issue and was able to solve it (or at least work around it).
If interested feel free to take a look over my blogpost: https://medium.com/@radicho/how-to-implement-admob-in-unity-a-bit-more-detailed-guide-4baed2821cce

**Comment by chauduyphanvu1** [comment]
This is no longer an issue with the fix released in `com.mopub.mediation:admob:15.0.0.1`. You shouldn't be seeing it again (you might be getting other `ClassNotFoundException` exceptions but the classname should be different, which would mean different issues). Thanks for sharing your blog post, though!
