### ISSUE TITLE
FacebookInterstitial  NullPointerException

### ISSUE THREAD

**Issue by keenlee123** [mopub/mopub-android-mediation#6]
FATAL EXCEPTION: main
                                                                         Process: com.mopub.simpleadsdemo, PID: 26526
                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'void com.mopub.mobileads.CustomEventInterstitial$CustomEventInterstitialListener.onInterstitialFailed(com.mopub.mobileads.MoPubErrorCode)' on a null object reference
                                                                             at com.mopub.mobileads.FacebookInterstitial.onError(FacebookInterstitial.java:118)
                                                                             at com.facebook.ads.InterstitialAd$1.a(Unknown Source)
                                                                             at com.facebook.ads.internal.DisplayAdController$3.run(Unknown Source)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6175)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by chauduyphanvu1** [comment]
Thanks for surfacing this crash! Do you have details such as the workflow that leads to this crash?
