### ISSUE TITLE
OneByAOL Sdk Android 8.0 crash

### ISSUE THREAD

**Issue by erkangur** [mopub/mopub-android-mediation#65]
Hello, 

Recently we upgraded our target sdk to 27, and started getting following crashes. All of those crashes happen in a Android 8.0.0 and 8.1.0. As I investigated it seems like SDK uses old scheduler APIs and doing a job which is not whitelisted (https://developer.android.com/about/versions/oreo/background). Is this related to you guys? 

I am using
`compile 'com.mopub.mediation:onebyaol:6.7.0.0'`
`compile 'com.millennialmedia:ads:6.8.0'`

```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.mypackage/com.millennialmedia.internal.VolumeChangeService }: app is in background uid UidRecord{85b24a7 u0a175 TRNB bg:+1h36m44s966ms idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1532)
       at android.app.ContextImpl.startService(ContextImpl.java:1488)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.millennialmedia.internal.VolumeChangeManager.start(VolumeChangeManager.java:97)
       at com.millennialmedia.internal.MMWebView.<init>(MMWebView.java:448)
       at com.millennialmedia.internal.adcontrollers.WebController.createWebView(WebController.java:369)
       at com.millennialmedia.internal.adcontrollers.WebController$1.run(WebController.java:123)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6695)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
```

**Comment by chauduyphanvu1** [comment]
@erkangur - thanks for the report. Do you have the steps to reproduce the crash? Which ad format is it? Do you still see the crash with `com.mopub.mediation:onebyaol:6.8.1.2` and One by AOL 6.8.1?

Also, I don't see any reference to MoPub in the stack trace.

**Comment by erkangur** [comment]
@chauduyphanvu1 I am not sure, we have updated the dependencies and released a version, now waiting for people to update. I can inform you later if crash persists. Reproduction is simple, according to my logs, user's simply try to watch a video through Mopub, if the next video happens to be AOL, it crashes (i do not know if this happens all the time for AOL videos).

**Comment by chauduyphanvu1** [comment]
@erkangur - thanks, I checked it out using the latest SDK + adapter versions, and did not see this crash with our test AOL rewarded video. Let us know if you run into the crash again. 

Out of curiosity, what is your use case? Based on the `Not allowed to start service Intent` error message on Android 8, it appears your app is backgrounding while this happens? Does your app already use a number of background services at the same time already?

**Comment by chauduyphanvu1** [comment]
@erkangur - is this still happening/reproducible?

**Comment by chauduyphanvu1** [comment]
Closed as not reproducible. Feel free to reopen if needed.
